baudrate = 1000000

# # --- Network / addressing ---
# dotbot_address = "FFFFFFFFFFFFFFFF"
# gateway_address = "0000000000000000"
network_id = "A000"

# # --- Controller HTTP interface ---
# controller_http_protocol = "http"
# controller_http_hostname = "localhost"
# controller_http_port = 8000

# --- MQTT configuration ---
mqtt_host = "argus2.paris.inria.fr"
mqtt_port = 8884
mqtt_use_tls = true

# --- Runtime behavior ---
webbrowser = true
verbose = false
log_level = "info"
log_output = "pydotbot.log"


# --- Simulator ---
simulator_init_state_path = "simulator_init_state2.toml"
