[[dotbots]]
address = "BADCAFE111111111" # DotBot unique address
calibrated = true # optional, defaults to true
pos_x = 400_000 # [0, 1_000_000]
pos_y = 200_000 # [0, 1_000_000]
theta = 0.0 # [0.0, 2pi]

[[dotbots]]
address = "DEADBEEF22222222"
pos_x = 300_000
pos_y = 100_000
theta = 1.57

[[dotbots]]
address = "B0B0F00D33333333"
pos_x = 1_000_000
pos_y = 1_000_000
theta = 1.57

[[dotbots]]
address = "BADC0DE444444444"
pos_x = 500_000
pos_y = 500_000
theta = 3.14

[[dotbots]]
address = "5555555555555555"
pos_x = 10_000
pos_y = 870_000
theta = 3.14


[[dotbots]]
address = "6666666666666666"
pos_x = 280_000
pos_y = 880_000
theta = 3.14


[[dotbots]]
address = "7777777777777777"
pos_x = 120_000
pos_y = 90_000
theta = 3.14


[[dotbots]]
address = "8888888888888888"
pos_x = 800_000
pos_y = 560_000
theta = 3.14

[[dotbots]]
address = "9999999999999999"
pos_x = 990_000
pos_y = 180_000
theta = 1.14


[[dotbots]]
address = "A000000000000000"
pos_x = 880_000
pos_y = 80_000
theta = 2.14
